inrootfile1="/home/pku/yuxd/bond/PKMUON_G4sim/DM_step1/build/root_file/muCRY.root"
intxtfiledir="/data/bond/yimengzhang/GEM/MuHitDM-11.20"
intxtfile=(""
"Mu_out_Constant(mDM=0.005GeV).dat"
"Mu_out_Constant(mDM=0.05GeV).dat"
"Mu_out_Constant(mDM=0.1GeV).dat"
"Mu_out_Constant(mDM=0.2GeV).dat"
"Mu_out_Constant(mDM=0.5GeV).dat"
"Mu_out_Constant(mDM=1.0GeV).dat"
"Mu_out_Constant(mDM=10.0GeV).dat"
"Mu_out_Constant(mDM=100.0GeV).dat"
"Mu_out_Maxwell(mDM=0.005GeV).dat"
"Mu_out_Maxwell(mDM=0.05GeV).dat"
"Mu_out_Maxwell(mDM=0.1GeV).dat"
"Mu_out_Maxwell(mDM=0.2GeV).dat"
"Mu_out_Maxwell(mDM=0.5GeV).dat"
"Mu_out_Maxwell(mDM=1.0GeV).dat"
"Mu_out_Maxwell(mDM=10.0GeV).dat"
"Mu_out_Maxwell(mDM=100.0GeV).dat"
)

inrootfile1dir="/home/pku/yuxd/bond/PKMUON_G4sim/DM_step2/build/root_file"
inrootfile=("constant/DMmuon_const_0p005.root"
"constant/DMmuon_const_0p05.root"
"constant/DMmuon_const_0p1.root"
"constant/DMmuon_const_0p2.root"
"constant/DMmuon_const_0p5.root"
"constant/DMmuon_const_1.root"
"constant/DMmuon_const_10.root"
"constant/DMmuon_const_100.root"
"maxwell/DMmuon_maxwell_0p005.root"
"maxwell/DMmuon_maxwell_0p05.root"
"maxwell/DMmuon_maxwell_0p1.root"
"maxwell/DMmuon_maxwell_0p2.root"
"maxwell/DMmuon_maxwell_0p5.root"
"maxwell/DMmuon_maxwell_1.root"
"maxwell/DMmuon_maxwell_10.root"
"maxwell/DMmuon_maxwell_100.root"
)

outrootfile=("../root/DMmuon_const_0p005.root"
"../root/DMmuon_const_0p05.root"
"../root/DMmuon_const_0p1.root"
"../root/DMmuon_const_0p2.root"
"../root/DMmuon_const_0p5.root"
"../root/DMmuon_const_1.root"
"../root/DMmuon_const_10.root"
"../root/DMmuon_const_100.root"
"../root/DMmuon_maxwell_0p005.root"
"../root/DMmuon_maxwell_0p05.root"
"../root/DMmuon_maxwell_0p1.root"
"../root/DMmuon_maxwell_0p2.root"
"../root/DMmuon_maxwell_0p5.root"
"../root/DMmuon_maxwell_1.root"
"../root/DMmuon_maxwell_10.root"
"../root/DMmuon_maxwell_100.root"
)

for (( i=0; i<${#intxtfile[@]}; i++ ))
do
  echo ${inrootfile1} ${intxtfiledir}/${intxtfile[$i]} ${inrootfile1dir}/${inrootfile[$i]} ${outrootfile[$i]}
  root -b -q -l analysis.cc'('\"${inrootfile1}\"','\"${intxtfiledir}/${intxtfile[$i]}\"','\"${inrootfile1dir}/${inrootfile[$i]}\"','\"${outrootfile[$i]}\"')'
done
